# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"InvisibleTensor": "00_data.ipynb",
         "generate_noise": "00_data.ipynb",
         "get_dls": "00_data.ipynb"}

modules = ["data.py"]

doc_url = "https://numb3r33.github.io/dcgan/"

git_url = "https://github.com/numb3r33/dcgan/tree/main/"

def custom_doc_links(name): return None
