# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"InvisibleTensor": "00_data.ipynb",
         "generate_noise": "00_data.ipynb",
         "get_dls": "00_data.ipynb",
         "build_conv_layer": "01_models.ipynb",
         "build_bn": "01_models.ipynb",
         "dcgan_generator": "01_models.ipynb",
         "build_mnist_gen_arch": "01_models.ipynb",
         "dcgan_discriminator": "01_models.ipynb",
         "build_mnist_disc_arch": "01_models.ipynb",
         "DCGAN": "01_models.ipynb",
         "DCGANLoss": "02_train.ipynb",
         "DCGANTrainer": "02_train.ipynb",
         "ShowDCGANImgsCallback": "02_train.ipynb"}

modules = ["data.py",
           "models.py",
           "train.py"]

doc_url = "https://numb3r33.github.io/dcgan/"

git_url = "https://github.com/numb3r33/dcgan/tree/main/"

def custom_doc_links(name): return None
