# AUTOGENERATED! DO NOT EDIT! File to edit: 00_data.ipynb (unless otherwise specified).

__all__ = ['InvisibleTensor', 'generate_noise', 'get_dls']

# Cell
from fastai.vision.all import *

# Cell
class InvisibleTensor(TensorBase):
    def show(self, ctx=None, **kwargs): return ctx

def generate_noise(fn, size=64): return cast(torch.randn(size).view(-1, 1, 1), InvisibleTensor)

# Cell
def get_dls(path, bs=4, num_workers=2):
    """
    Given image path, load the images.
    Batch size is specified by `bs` (default=4).
    """
    dblock = DataBlock(blocks = (TransformBlock, ImageBlock(cls=PILImageBW)),
                       get_x = generate_noise,
                       get_items = get_image_files,
                       splitter = IndexSplitter([]),
                       batch_tfms=Normalize.from_stats(mean=0.5, std=0.5)
                   )

    dls = dblock.dataloaders(path, path=path, bs=bs, num_workers=num_workers)

    return dls